spring:
  redis:
    port: 6379
  application:
    name: oredr-server
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true